_target_: streamlet.optimizers.Implicit
name: ???
cfg:
  _target_: streamlet.optimizers.ImplicitConfig
  gamma: ???
  trace_lambda: ???
  eta: ???
  kappa: 1.0
  curvature_mode: full
  beta2: 0.999
  eps: 1e-8
