[project]
name = "recurrent-streaming-rl"
version = "0.1.0"
description = "Recurrent Streaming Reinforcement Learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "streamlet",
    "popgymnax",
    "gymnasium-ffi",
    "distrax>=0.1.5",
    "flashbax>=0.1.3",
    "hydra-core>=1.3.2",
    "hydra-slurmpilot-launcher",
    "omegaconf>=2.3.0",
    "ale-py[xla]>=0.12.1",
]

[project.optional-dependencies]
sweeps = [
    "hydra-optuna-sweeper==1.4.0.dev8",
    "submitit>=1.5.4",
    "raylib>=6.0.1.0",
]

[tool.uv]
override-dependencies = ["lox"]

[tool.uv.sources]
lox = { git = "https://github.com/huterguier/lox", branch = "dev" }
popgymnax = { git = "https://github.com/noahfarr/popgymnax.git" }
gymnasium-ffi = { git = "https://github.com/noahfarr/gymnasium-ffi.git" }
streamlet = { git = "ssh://git@github.com/noahfarr/streamlet.git" }
hydra-slurmpilot-launcher = { git = "ssh://git@github.com/noahfarr/hydra-slurmpilot-launcher.git" }
slurmpilot = { git = "https://github.com/noahfarr/slurmpilot.git", branch = "feat/spignore" }

[tool.setuptools.packages.find]
include = ["src*"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
