defaults:
  - slurmpilot
  - _self_

cluster: mock
partition: null

n_cpus: 1
max_runtime_minutes: 5

python_binary: ${oc.env:HOME}/recurrent-streaming-rl/.venv/bin/python

env:
  XLA_PYTHON_CLIENT_PREALLOCATE: "false"
  XLA_PYTHON_CLIENT_ALLOCATOR: cuda_async

wait: true
wait_max_seconds: 300
