# @package _global_

total_timesteps: 2_000_000
num_epochs: 20

algorithm:
  num_envs: 1
  num_steps: 2048
  gae_lambda: 0.95
  num_minibatches: 32
  update_epochs: 4
  normalize_advantage: True
  clip_coefficient: 0.2
  clip_value_loss: True
  entropy_coefficient: 0.0

