# @package _global_

algorithm:
  num_envs: 32
  num_steps: 64
  num_minibatches: 32
  update_epochs: 4
  gamma: 0.99
  gae_lambda: 0.95
  clip_coefficient: 0.2
  clip_value_loss: true
  normalize_advantage: true
  entropy_coefficient: 0.0

actor_lr: 3e-4
critic_lr: 1e-4

total_timesteps: 5_000_000
num_epochs: 25
