# @package _global_

defaults:
  - /optimizer@actor_optimizer: obgd
  - /optimizer@critic_optimizer: obgd
  - _self_

algorithm:
  _target_: streamlet.algorithms.RecurrentACLambdaConfig
  gamma: 0.99
  trace_lambda: 0.8
  entropy_coefficient: 0.01

actor_optimizer:
  name: actor_optimizer
  cfg:
    lr: 1.0
    kappa: 1.5
critic_optimizer:
  name: critic_optimizer
  cfg:
    lr: 1.0
    kappa: 1.0
