# @package _global_
defaults:
  - /optimizer@actor_optimizer: adamw
  - /optimizer@critic_optimizer: adamw
  - /optimizer@alpha_optimizer: adam
  - _self_

algorithm:
  _target_: src.algorithms.fast_sac.FastSACConfig
  num_envs: 1
  gamma: 0.97
  tau: 0.005
  train_frequency: 1
  target_update_frequency: 1
  target_entropy_scale: 0.0
  batch_size: 256
  buffer_size: 1_000_000
  sequence_length: 8
  gradient_steps: 1
  num_critics: 2
  num_atoms: 51
  v_min: -10.0
  v_max: 10.0

actor_optimizer:
  name: actor_optimizer
  lr: 3e-4
  b2: 0.95
  weight_decay: 0.001
critic_optimizer:
  name: critic_optimizer
  lr: 3e-4
  b2: 0.95
  weight_decay: 0.001
alpha_optimizer:
  name: alpha_optimizer
  lr: 3e-4
