# @package _global_

algorithm:
  _target_: src.algorithms.stream_ac.StreamACConfig
  name: stream_ac
  num_envs: 1
  gamma: 0.99
  trace_lambda: 0.8
  actor_lr: 1.0
  critic_lr: 1.0
  actor_kappa: 1.5
  critic_kappa: 1.0
  entropy_coefficient: 0.01
  adaptive: false
  beta2: 0.999
  eps: 1e-8
  track: false
  staleness_interval: 1
  taylor_trace: false
