namespace: ale
suite: ale
env_id: breakout
kwargs:
  episodic_life: false
wrappers:
  - _target_: src.environments.wrappers.EpisodicLife
  - _target_: src.environments.wrappers.FireReset
    fire_action: 1
