total_timesteps: 500_000
num_epochs: 10
num_episodes: 0
learning_starts: 0
seed: 0
num_seeds: 1

groups: ${groups:}

loggers: {}

hydra:
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}-${oc.env:SLURM_ARRAY_TASK_ID,0}

defaults:
  - _self_
  - algorithm: ppo
  - environment: popgymnax/repeat_first/easy
  - cell: ffn
  - mode: bptt
  - network: shared
  - logger: default
  - experiment: null
  - optional hyperparameters: ${cascading_fallback:hyperparameters,${algorithm},${environment},${cell}}

