# @package hydra.sweeper

params:
  algorithm.trace_lambda: interval(0.5, 0.99)
  algorithm.regularization_coefficient: tag(log, interval(0.1, 10.0))
  q_optimizer.lr: tag(log, interval(1e-5, 1e-2))
  q_optimizer.max_grad_norm: tag(log, interval(0.1, 10.0))
  h_optimizer.lr: tag(log, interval(1e-6, 1e-3))
  h_optimizer.max_grad_norm: tag(log, interval(0.1, 10.0))
  epsilon_fraction: interval(0.05, 0.5)
  cell.config.hidden_dim: choice(64, 128, 256, 384)
