# @package _global_

sweep:
  metric: score
  cost: cost
  num_trials: 64
  num_jobs: 8
  cluster: null
  prior_score: null
  prior_cost: null
  executor:
    timeout_min: 720
    cpus_per_task: 2
    gpus_per_node: 1
    mem_gb: 16
    slurm_partition: null
    slurm_exclude: dgx-station
  carbs:
    _target_: carbs.CARBSParams
    seed: 42
    num_random_samples: 10
    resample_frequency: 5
    max_suggestion_cost: 14400
    is_wandb_logging_enabled: false
    is_saved_on_every_observation: false
  params:
    algorithm.trace_lambda: {distribution: uniform, min: 0.5, max: 0.99, scale: auto}
    algorithm.regularization_coefficient: {distribution: log_normal, min: 0.1, max: 10.0, scale: auto}
    q_optimizer.lr: {distribution: log_normal, min: 1.0e-5, max: 1.0e-2, scale: auto}
    q_optimizer.max_grad_norm: {distribution: log_normal, min: 0.1, max: 10.0, scale: auto}
    h_optimizer.lr: {distribution: log_normal, min: 1.0e-6, max: 1.0e-3, scale: auto}
    h_optimizer.max_grad_norm: {distribution: log_normal, min: 0.1, max: 10.0, scale: auto}
    epsilon_fraction: {distribution: uniform, min: 0.05, max: 0.5, scale: auto}
    cell.config.hidden_dim: {distribution: uniform_pow2, min: 64, max: 384, scale: auto}
