# @package hydra.launcher
defaults:
  - gpu
  - _self_

# v100 lives only on dgx-station, so this device must NOT exclude it.
sbatch_arguments: "--output=logs/stdout-%a --error=logs/stderr-%a --constraint=v100"
