_target_: src.cells.RTUCell
name: rtu
config:
  _target_: src.cells.RTUConfig
  features: 64
  hidden_dim: 192
  r_min: 0.0
  r_max: 1.0
  activation_fn:
    _target_: src.utils.identity.identity
    _partial_: true
  output_activation_fn:
    _target_: jax.numpy.tanh
    _partial_: true
